name: Deploy Neonx CLI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Lier le package localement
      - name: Link package locally
        run: npm link

      # Publier le package sur npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
